### ISSUE TITLE
Adding a map to the basic viewer template

### ISSUE THREAD

**Issue by RohillaSaurabh** [Esri/basic-viewer-template#21]
Hi

I want to add my base map.But i am able to see only webmap id which i didnt have.
I wan to add map like this
var myMap = new esri.Map("mapDiv");
Where to write this code??

**Comment by kellyhutchins** [comment]
This template is setup to work with web maps created using ArcGIS Online. If you don't already have an account for ArcGIS Online you can sign up for a developers account to test it out. More info is here: 
https://developers.arcgis.com/sign-up/
